# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liftpart',
            name='full_description',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
    ]
