# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifts', '0003_remove_liftpart_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='liftpart',
            name='kind',
            field=models.IntegerField(choices=[(1, '\u041b\u0418\u0424\u0422\u041e\u0412\u042b\u0415 \u0417\u0410\u041f\u0427\u0410\u0421\u0422\u0418'), (2, '\u041b\u0418\u0424\u0422\u041e\u0412\u042b\u0415 \u041f\u041b\u0410\u0422\u042b'), (3, 'OTIS \u0417\u0410\u041f\u0427\u0410\u0421\u0422\u0418')], null=True),
        ),
    ]
